language: node_js
node_js:
  - "stable"

branches:
  only:
    - develop

before_script:
  - npm install
  - npm install supertest nyc

services:
  - postgresql

after_success:
  - npm install istanbul
  - npm install coveralls
  - npm run coveralls
