language: node_js
node_js:
  - "stable"

branches:
  only:
    - develop

before_script:
  - npm install
  - npm install supertest nyc
  - curl -L http://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

services:
  - postgresql

after_success:
  - npm install istanbul
  - npm install coveralls
  - npm run coveralls
  - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
  - ./cc-test-reporter upload-coverage
